alter table public.challenges
  add column camera_roll_enabled boolean not null default false;

update public.challenges set camera_roll_enabled = true where is_showcase;

create table public.shared_moments (
  id uuid primary key,
  challenge_id uuid not null references public.challenges(id) on delete cascade,
  creator_id uuid not null references auth.users(id) on delete cascade,
  editorial_category text,
  note text,
  media_path text,
  attribution text not null default 'anonymous',
  reveal_consent boolean not null default true,
  export_consent boolean not null default false,
  media_version integer not null default 1,
  consent_version integer not null default 1,
  lifecycle text not null default 'upload_pending',
  reported_at timestamptz,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint shared_moments_category check (editorial_category is null or editorial_category in ('encouragement','giving','community','teaching','support','connection')),
  constraint shared_moments_note_length check (note is null or char_length(note) <= 280),
  constraint shared_moments_attribution check (attribution in ('anonymous','permitted')),
  constraint shared_moments_lifecycle check (lifecycle in ('local_draft','upload_pending','sealed_pending_review','approved','rejected','deleted','reported','consent_revoked')),
  constraint shared_moments_media_versions check (media_version > 0 and consent_version > 0),
  constraint shared_moments_remote_not_local check (lifecycle <> 'local_draft')
);

create index shared_moments_challenge_state_idx on public.shared_moments(challenge_id, lifecycle, created_at);
create index shared_moments_creator_idx on public.shared_moments(creator_id, challenge_id, created_at desc);
create unique index shared_moments_media_path_unique on public.shared_moments(media_path) where media_path is not null;

create table public.shared_moment_reports (
  moment_id uuid not null references public.shared_moments(id) on delete cascade,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (moment_id, reporter_id)
);

create table public.shared_roll_counts (
  challenge_id uuid primary key references public.challenges(id) on delete cascade,
  sealed_count integer not null default 0,
  approved_count integer not null default 0,
  updated_at timestamptz not null default now()
);

create table public.engagement_events (
  id bigint generated by default as identity primary key,
  actor_id uuid not null references auth.users(id) on delete cascade,
  challenge_id uuid not null references public.challenges(id) on delete cascade,
  client_event_id uuid not null,
  name text not null,
  occurred_at timestamptz not null default now(),
  constraint engagement_events_allowlist check (name in (
    'camera_impression','camera_open','shutter','review','sealed','reminder_opt_in',
    'reveal_open','recap_open','recap_export','recap_share'
  )),
  constraint engagement_events_deduplicated unique (actor_id, client_event_id)
);

create index engagement_events_expiry_idx on public.engagement_events(occurred_at);

alter table public.shared_moments enable row level security;
alter table public.shared_moment_reports enable row level security;
alter table public.shared_roll_counts enable row level security;
alter table public.engagement_events enable row level security;

create policy "owners organizers and revealed members read shared moments"
on public.shared_moments for select to authenticated using (
  creator_id = (select auth.uid())
  or private.is_challenge_organizer(challenge_id)
  or (
    private.is_challenge_member(challenge_id)
    and lifecycle = 'approved' and reveal_consent and deleted_at is null and reported_at is null
    and exists (select 1 from public.challenges c where c.id = challenge_id and c.status = 'revealed')
  )
);

create policy "members create their own shared moments"
on public.shared_moments for insert to authenticated with check (
  creator_id = (select auth.uid()) and lifecycle = 'upload_pending'
  and private.is_challenge_member(challenge_id)
  and exists (select 1 from public.challenges c where c.id = challenge_id and c.camera_roll_enabled and c.status = 'active')
);

create policy "owners update their shared moments"
on public.shared_moments for update to authenticated
using (creator_id = (select auth.uid())) with check (creator_id = (select auth.uid()));

create policy "organizers moderate shared moments"
on public.shared_moments for update to authenticated
using (private.is_challenge_organizer(challenge_id)) with check (private.is_challenge_organizer(challenge_id));

create policy "members report revealed moments"
on public.shared_moment_reports for insert to authenticated with check (
  reporter_id = (select auth.uid()) and exists (
    select 1 from public.shared_moments sm
    where sm.id = moment_id and private.is_challenge_member(sm.challenge_id)
  )
);

create policy "organizers read shared moment reports"
on public.shared_moment_reports for select to authenticated using (
  exists (select 1 from public.shared_moments sm where sm.id = moment_id and private.is_challenge_organizer(sm.challenge_id))
);

create policy "members read sealed counts"
on public.shared_roll_counts for select to authenticated using (private.is_challenge_member(challenge_id));

create policy "clients append allowlisted engagement only"
on public.engagement_events for insert to authenticated with check (
  actor_id = (select auth.uid()) and private.is_challenge_member(challenge_id)
);

create function private.guard_shared_moment_update()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if old.creator_id <> new.creator_id or old.challenge_id <> new.challenge_id or old.created_at <> new.created_at then
    raise exception 'immutable shared moment ownership';
  end if;
  if not private.is_challenge_organizer(old.challenge_id) then
    if new.lifecycle not in ('upload_pending','sealed_pending_review','approved','deleted','consent_revoked') then
      raise exception 'invalid owner lifecycle transition';
    end if;
    if new.lifecycle = 'approved' and old.lifecycle <> 'approved' then
      raise exception 'only organizers approve shared moments';
    end if;
    if old.reported_at is distinct from new.reported_at then raise exception 'reported state is server managed'; end if;
    new.consent_version := old.consent_version + case when old.reveal_consent is distinct from new.reveal_consent or old.export_consent is distinct from new.export_consent then 1 else 0 end;
  end if;
  new.updated_at := now();
  return new;
end;
$$;

create trigger guard_shared_moment_update before update on public.shared_moments
for each row execute function private.guard_shared_moment_update();

create function private.flag_shared_moment_report()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  update public.shared_moments set reported_at = now(), lifecycle = 'reported' where id = new.moment_id;
  return new;
end;
$$;
create trigger flag_shared_moment_report after insert on public.shared_moment_reports
for each row execute function private.flag_shared_moment_report();

create function private.refresh_shared_roll_count()
returns trigger language plpgsql security definer set search_path = '' as $$
declare target uuid := coalesce(new.challenge_id, old.challenge_id);
begin
  insert into public.shared_roll_counts(challenge_id, sealed_count, approved_count, updated_at)
  select target,
    count(*) filter (where lifecycle in ('upload_pending','sealed_pending_review','approved')),
    count(*) filter (where lifecycle = 'approved' and reveal_consent and deleted_at is null and reported_at is null), now()
  from public.shared_moments where challenge_id = target
  on conflict (challenge_id) do update set sealed_count = excluded.sealed_count,
    approved_count = excluded.approved_count, updated_at = excluded.updated_at;
  return coalesce(new, old);
end;
$$;
create trigger refresh_shared_roll_count after insert or update or delete on public.shared_moments
for each row execute function private.refresh_shared_roll_count();

create function private.prune_engagement_events()
returns integer language plpgsql security definer set search_path = '' as $$
declare removed integer;
begin
  delete from public.engagement_events where occurred_at < now() - interval '30 days';
  get diagnostics removed = row_count;
  return removed;
end;
$$;

drop view public.recap_sources;
create view public.recap_sources with (security_invoker = true) as
select m.id, 'contribution'::text as origin, m.contribution_id, c.challenge_id, co.participant_id,
  case when m.show_identity then nullif(cm.display_name, '') else null end as participant_display_name,
  m.show_identity as attribution_allowed, mission.category, coalesce(m.approved_at, c.updated_at) as accepted_at,
  m.media_path, m.story_text, c.emotion::text as emotion, c.tile_position, false as is_revived,
  m.media_version, m.consent_version, (c.status in ('verified','placed','revealed')) as accepted,
  m.export_consent as recap_consent, (m.media_path is not null or m.story_text is not null) as media_exists,
  (m.deleted_at is not null) as is_deleted, (m.reported_at is not null) as is_reported,
  exists (select 1 from public.user_blocks ub where ub.blocker_id = (select auth.uid()) and ub.blocked_id = co.participant_id) as contributor_is_blocked
from public.memories m join public.contributions c on c.id = m.contribution_id
join public.contribution_owners co on co.contribution_id = c.id join public.missions mission on mission.id = c.mission_id
left join public.challenge_members cm on cm.challenge_id = c.challenge_id and cm.user_id = co.participant_id
join public.challenges challenge on challenge.id = c.challenge_id
where challenge.status = 'revealed' and m.review_status = 'approved' and m.export_consent
  and m.deleted_at is null and m.reported_at is null
  and not exists (select 1 from public.user_blocks ub where ub.blocker_id = (select auth.uid()) and ub.blocked_id = co.participant_id)
union all
select sm.id, 'shared_moment'::text, null::uuid, sm.challenge_id, sm.creator_id,
  case when sm.attribution = 'permitted' then nullif(cm.display_name, '') else null end,
  sm.attribution = 'permitted', sm.editorial_category, sm.created_at, sm.media_path, sm.note,
  null::text, null::integer, false, sm.media_version, sm.consent_version, true, sm.export_consent,
  sm.media_path is not null, sm.deleted_at is not null, sm.reported_at is not null,
  exists (select 1 from public.user_blocks ub where ub.blocker_id = (select auth.uid()) and ub.blocked_id = sm.creator_id)
from public.shared_moments sm join public.challenges c on c.id = sm.challenge_id
left join public.challenge_members cm on cm.challenge_id = sm.challenge_id and cm.user_id = sm.creator_id
where c.status = 'revealed' and sm.lifecycle = 'approved' and sm.reveal_consent and sm.export_consent
  and sm.deleted_at is null and sm.reported_at is null
  and not exists (select 1 from public.user_blocks ub where ub.blocker_id = (select auth.uid()) and ub.blocked_id = sm.creator_id);

revoke all on public.shared_moments, public.shared_moment_reports, public.shared_roll_counts, public.engagement_events from anon, authenticated;
grant select, insert, update on public.shared_moments to authenticated;
grant select, insert on public.shared_moment_reports to authenticated;
grant select on public.shared_roll_counts to authenticated;
grant insert on public.engagement_events to authenticated;
grant select on public.recap_sources to authenticated;
grant all on public.shared_moments, public.shared_moment_reports, public.shared_roll_counts, public.engagement_events to service_role;
revoke all on function private.prune_engagement_events() from public, anon, authenticated;
grant execute on function private.prune_engagement_events() to service_role;

create policy "moment owners upload recap memories"
on storage.objects for insert to authenticated with check (
  bucket_id = 'recap-memories' and (storage.foldername(name))[1] = 'moments'
  and (storage.foldername(name))[3] = (select auth.uid())::text
  and exists (select 1 from public.shared_moments sm where sm.creator_id = (select auth.uid()) and sm.media_path = name)
);
create policy "moment owners replace queued recap memories"
on storage.objects for update to authenticated using (
  bucket_id = 'recap-memories' and exists (select 1 from public.shared_moments sm where sm.creator_id = (select auth.uid()) and sm.media_path = name)
) with check (
  bucket_id = 'recap-memories' and exists (select 1 from public.shared_moments sm where sm.creator_id = (select auth.uid()) and sm.media_path = name)
);
create policy "authorized members read revealed moments"
on storage.objects for select to authenticated using (
  bucket_id = 'recap-memories' and exists (
    select 1 from public.shared_moments sm join public.challenges c on c.id = sm.challenge_id
    where sm.media_path = name and (
      sm.creator_id = (select auth.uid()) or private.is_challenge_organizer(sm.challenge_id)
      or (private.is_challenge_member(sm.challenge_id) and c.status = 'revealed' and sm.lifecycle = 'approved' and sm.reveal_consent)
    )
  )
);

do $$ begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'shared_roll_counts') then
    alter publication supabase_realtime add table public.shared_roll_counts;
  end if;
end $$;
